apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yaml
  - pvc.yaml
  - namespace.yaml
  - ./../../manifests
namespace: the-project-staging
patches:
  - path: rollout-patch.yaml
  - path: deployment-patch.yaml