apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 6d39ffae52671082fdad34b5a4681c962d6c9610
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 6d39ffae52671082fdad34b5a4681c962d6c9610
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 6d39ffae52671082fdad34b5a4681c962d6c9610
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 6d39ffae52671082fdad34b5a4681c962d6c9610

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
