apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 00f82ecd37125852ce17d3a9146bc0a8db8d68a5
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 00f82ecd37125852ce17d3a9146bc0a8db8d68a5
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 00f82ecd37125852ce17d3a9146bc0a8db8d68a5
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 00f82ecd37125852ce17d3a9146bc0a8db8d68a5

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/rollout.yaml
