apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 6224ae8c24b429448771ed55ead41bf86328e4b7
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 6224ae8c24b429448771ed55ead41bf86328e4b7
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 6224ae8c24b429448771ed55ead41bf86328e4b7
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 6224ae8c24b429448771ed55ead41bf86328e4b7

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml