apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 74069b9250c1a8519c2d4d652fd2bba5c1d87ca5
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 74069b9250c1a8519c2d4d652fd2bba5c1d87ca5
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 74069b9250c1a8519c2d4d652fd2bba5c1d87ca5
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 74069b9250c1a8519c2d4d652fd2bba5c1d87ca5

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
