apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 6ce29d9e79674f45cda473d82930cc15d83f24fe
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 6ce29d9e79674f45cda473d82930cc15d83f24fe
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 6ce29d9e79674f45cda473d82930cc15d83f24fe
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 6ce29d9e79674f45cda473d82930cc15d83f24fe

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
