apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: c8037c360af399a153acbd53de6808c4d5dacaab
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: c8037c360af399a153acbd53de6808c4d5dacaab
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: c8037c360af399a153acbd53de6808c4d5dacaab
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: c8037c360af399a153acbd53de6808c4d5dacaab

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
