apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: c4191bda9958b09eabbd595cfed7e27459de3669
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: c4191bda9958b09eabbd595cfed7e27459de3669
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: c4191bda9958b09eabbd595cfed7e27459de3669
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: c4191bda9958b09eabbd595cfed7e27459de3669

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/rollout.yaml
