apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 3ce0efb304329d2d0d5fe000fbfa4d11b65e3854
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 3ce0efb304329d2d0d5fe000fbfa4d11b65e3854
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 3ce0efb304329d2d0d5fe000fbfa4d11b65e3854
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 3ce0efb304329d2d0d5fe000fbfa4d11b65e3854

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/rollout.yaml
