apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: e18432fd66717c7b5735c785e043f9e4ba2dc156
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: e18432fd66717c7b5735c785e043f9e4ba2dc156
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: e18432fd66717c7b5735c785e043f9e4ba2dc156
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: e18432fd66717c7b5735c785e043f9e4ba2dc156

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
