apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 0e05bd41c2936cd8fab2315d156850df5ca61bac
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 0e05bd41c2936cd8fab2315d156850df5ca61bac
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 0e05bd41c2936cd8fab2315d156850df5ca61bac
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 0e05bd41c2936cd8fab2315d156850df5ca61bac

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
