apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: c895f19dedafc739e410ab987cbe93702a7685e5
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: c895f19dedafc739e410ab987cbe93702a7685e5
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: c895f19dedafc739e410ab987cbe93702a7685e5
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: c895f19dedafc739e410ab987cbe93702a7685e5

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
