apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 318e32a62a6cd1e340b6eb9a5bc35b708774cf56
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 318e32a62a6cd1e340b6eb9a5bc35b708774cf56
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 318e32a62a6cd1e340b6eb9a5bc35b708774cf56
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 318e32a62a6cd1e340b6eb9a5bc35b708774cf56

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
