apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 27a214366b9a51910f767e94ffcc51e421b403de
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 27a214366b9a51910f767e94ffcc51e421b403de
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 27a214366b9a51910f767e94ffcc51e421b403de
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 27a214366b9a51910f767e94ffcc51e421b403de

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
