apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 33e5a6db5b18f9252d15d56d73604fd8a3f41c55
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 33e5a6db5b18f9252d15d56d73604fd8a3f41c55
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 33e5a6db5b18f9252d15d56d73604fd8a3f41c55
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 33e5a6db5b18f9252d15d56d73604fd8a3f41c55

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
