apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 728bac52e1e0b1276d6498b03a9c02a44435ef02
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 728bac52e1e0b1276d6498b03a9c02a44435ef02
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 728bac52e1e0b1276d6498b03a9c02a44435ef02
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 728bac52e1e0b1276d6498b03a9c02a44435ef02

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
