apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
