apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 6689e2a306eef5b33cf7b2c30ee350c6321d8b0d
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 6689e2a306eef5b33cf7b2c30ee350c6321d8b0d
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 6689e2a306eef5b33cf7b2c30ee350c6321d8b0d
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 6689e2a306eef5b33cf7b2c30ee350c6321d8b0d

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
