apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 2e11597c6ed93d8f451dc1749218c5b4a1cedc9d
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 2e11597c6ed93d8f451dc1749218c5b4a1cedc9d
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 2e11597c6ed93d8f451dc1749218c5b4a1cedc9d
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 2e11597c6ed93d8f451dc1749218c5b4a1cedc9d

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
