apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 1529caeed713d4a52a4f69fda7d1ec9a710b3d2f
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 1529caeed713d4a52a4f69fda7d1ec9a710b3d2f
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 1529caeed713d4a52a4f69fda7d1ec9a710b3d2f
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 1529caeed713d4a52a4f69fda7d1ec9a710b3d2f

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
