apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 0179bb7a8150a7d4ecf83eaddbf44fc7d91b6095
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 0179bb7a8150a7d4ecf83eaddbf44fc7d91b6095
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 0179bb7a8150a7d4ecf83eaddbf44fc7d91b6095
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 0179bb7a8150a7d4ecf83eaddbf44fc7d91b6095

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/rollout.yaml
