apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 89dcd10d35a6038e211e2cbdec9f2fe0361c8b90
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 89dcd10d35a6038e211e2cbdec9f2fe0361c8b90
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 89dcd10d35a6038e211e2cbdec9f2fe0361c8b90
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 89dcd10d35a6038e211e2cbdec9f2fe0361c8b90

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
