apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: a8c6018f2f6a0cf4a6d99614bafe94878e762fd7
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: a8c6018f2f6a0cf4a6d99614bafe94878e762fd7
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: a8c6018f2f6a0cf4a6d99614bafe94878e762fd7
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: a8c6018f2f6a0cf4a6d99614bafe94878e762fd7

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
