apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
- name: TODO-BACKEND
  newName: njugen/todo-backend
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
- name: TODO-FRONTEND
  newName: njugen/todo-app

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/rollout.yaml