apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 24c7dfb6374c7e8b7765e713db46cee4df9d5191
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 24c7dfb6374c7e8b7765e713db46cee4df9d5191
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 24c7dfb6374c7e8b7765e713db46cee4df9d5191
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 24c7dfb6374c7e8b7765e713db46cee4df9d5191

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/service.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/rollout.yaml
