apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 2dacc62b50d156020a5b9c02703929404d6e28fa
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 2dacc62b50d156020a5b9c02703929404d6e28fa
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 2dacc62b50d156020a5b9c02703929404d6e28fa
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 2dacc62b50d156020a5b9c02703929404d6e28fa

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
