apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 9f8f8b1b13603b0c710beb899b162cada2c10ae0
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 9f8f8b1b13603b0c710beb899b162cada2c10ae0
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 9f8f8b1b13603b0c710beb899b162cada2c10ae0
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 9f8f8b1b13603b0c710beb899b162cada2c10ae0

resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/cronjob.yaml
- manifests/statefulset.yaml
- manifests/ingress.yaml
- manifests/pv.yaml
- manifests/pvc.yaml
- manifests/service.yaml
- manifests/rollout.yaml
