apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
data:
  storage.path.images: "/usr/src/files/images"
  images.datasrc: "https://picsum.photos/1200"
  images.staticfilename: "random-image"
  mimes.jpg: "image/jpg"
  mimes.jpeg: "image/jpeg"
  mimes.png: "image/png"
  mimes.gif: "image/gif"
  mimes.webp: "image/webp"
  cache.enabled: "false"
  cache.control: "no-store, no-cache, must-revalidate"
  cache.pragma: "no-cache"
  cache.expires: "0"
  todo.fields.todotextfield.length: "140"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "todo-db"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "123456"
  PGDATA: "/data/pgdata"
  NATS_URL: "nats://my-nats.default.svc.cluster.local:4222"
  MOCKAPIURL: "https://69763b0fc0c36a2a99509327.mockapi.io/throwaway"
  