apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 7bf2dc6a2edd14dcdd2481a764a48882da804b2e
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 7bf2dc6a2edd14dcdd2481a764a48882da804b2e
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 7bf2dc6a2edd14dcdd2481a764a48882da804b2e
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 7bf2dc6a2edd14dcdd2481a764a48882da804b2e
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 7bf2dc6a2edd14dcdd2481a764a48882da804b2e

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
