apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 42af7d879b79a79bc27bbc3f7544a44e2e76df75
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 42af7d879b79a79bc27bbc3f7544a44e2e76df75
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 42af7d879b79a79bc27bbc3f7544a44e2e76df75
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 42af7d879b79a79bc27bbc3f7544a44e2e76df75
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 42af7d879b79a79bc27bbc3f7544a44e2e76df75

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
