apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 9d135ab487c759a612060f91ccc7be4cc39fb139
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 9d135ab487c759a612060f91ccc7be4cc39fb139
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 9d135ab487c759a612060f91ccc7be4cc39fb139
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 9d135ab487c759a612060f91ccc7be4cc39fb139
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 9d135ab487c759a612060f91ccc7be4cc39fb139

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
