apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 54ef1af7f67dcc895b38b7f8bb53da7472023a0b
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 54ef1af7f67dcc895b38b7f8bb53da7472023a0b
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 54ef1af7f67dcc895b38b7f8bb53da7472023a0b
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 54ef1af7f67dcc895b38b7f8bb53da7472023a0b
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 54ef1af7f67dcc895b38b7f8bb53da7472023a0b

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
