apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: e27c218342c81eb543c8723075950bd840aaac94
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: e27c218342c81eb543c8723075950bd840aaac94
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: e27c218342c81eb543c8723075950bd840aaac94
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: e27c218342c81eb543c8723075950bd840aaac94
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: e27c218342c81eb543c8723075950bd840aaac94

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
