apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 997f85918ad4ba48229821ef040df145b82ef207
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 997f85918ad4ba48229821ef040df145b82ef207
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 997f85918ad4ba48229821ef040df145b82ef207
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 997f85918ad4ba48229821ef040df145b82ef207
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 997f85918ad4ba48229821ef040df145b82ef207

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
