apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: e2585dce39403b7328a5e9d209bbd3f7eb97198e
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: e2585dce39403b7328a5e9d209bbd3f7eb97198e
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: e2585dce39403b7328a5e9d209bbd3f7eb97198e
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: e2585dce39403b7328a5e9d209bbd3f7eb97198e
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: e2585dce39403b7328a5e9d209bbd3f7eb97198e

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
