apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: c1f1e0b5dbc6cf2c95ce9cfefe2d688d07de210d
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: c1f1e0b5dbc6cf2c95ce9cfefe2d688d07de210d
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: c1f1e0b5dbc6cf2c95ce9cfefe2d688d07de210d
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: c1f1e0b5dbc6cf2c95ce9cfefe2d688d07de210d
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: c1f1e0b5dbc6cf2c95ce9cfefe2d688d07de210d

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
