apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: e8fce98fe4526af88eafca8d2b7862cd41563151
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 97f8875d4fe7758e633a3a4b3392f39fd18a8a0b
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 97f8875d4fe7758e633a3a4b3392f39fd18a8a0b
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 97f8875d4fe7758e633a3a4b3392f39fd18a8a0b

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
