apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 9b8de9573ff080e481effee4ea6a5dcb22ba0987
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 9b8de9573ff080e481effee4ea6a5dcb22ba0987
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 9b8de9573ff080e481effee4ea6a5dcb22ba0987
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 9b8de9573ff080e481effee4ea6a5dcb22ba0987
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 9b8de9573ff080e481effee4ea6a5dcb22ba0987

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
