apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: ce624f04b88531b10096935a5ffb16140be44ea6
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: ce624f04b88531b10096935a5ffb16140be44ea6
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: ce624f04b88531b10096935a5ffb16140be44ea6
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: ce624f04b88531b10096935a5ffb16140be44ea6
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: ce624f04b88531b10096935a5ffb16140be44ea6

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
