apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 95221c50fb7ff84ccb9f3978301da31088bccc7a
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 95221c50fb7ff84ccb9f3978301da31088bccc7a
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 95221c50fb7ff84ccb9f3978301da31088bccc7a
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 95221c50fb7ff84ccb9f3978301da31088bccc7a
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 95221c50fb7ff84ccb9f3978301da31088bccc7a

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
