apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 435d8f114285946ba05937c3c1276ad340ca9acf
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 435d8f114285946ba05937c3c1276ad340ca9acf
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 435d8f114285946ba05937c3c1276ad340ca9acf
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 435d8f114285946ba05937c3c1276ad340ca9acf
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 435d8f114285946ba05937c3c1276ad340ca9acf

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
