apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 5e5507425de0e73d925bbc80ea42e4ed024b5c7f
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 5e5507425de0e73d925bbc80ea42e4ed024b5c7f
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 5e5507425de0e73d925bbc80ea42e4ed024b5c7f
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 5e5507425de0e73d925bbc80ea42e4ed024b5c7f
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 5e5507425de0e73d925bbc80ea42e4ed024b5c7f

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
