apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: a31ae1e1dffb6e2d991d733e4513bc1230f1b25e

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- pv.yaml
- pvc.yaml
- service.yaml
- rollout.yaml
