apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 9fcfee2a7ffa4f1c76956024ae01f71ba0cbf1b7
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 9fcfee2a7ffa4f1c76956024ae01f71ba0cbf1b7
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 9fcfee2a7ffa4f1c76956024ae01f71ba0cbf1b7
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 9fcfee2a7ffa4f1c76956024ae01f71ba0cbf1b7
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 9fcfee2a7ffa4f1c76956024ae01f71ba0cbf1b7

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
