apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 238dfa5983d18dcf2d2be7df8d10c48e0c526069
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 238dfa5983d18dcf2d2be7df8d10c48e0c526069
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 238dfa5983d18dcf2d2be7df8d10c48e0c526069
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 238dfa5983d18dcf2d2be7df8d10c48e0c526069
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 238dfa5983d18dcf2d2be7df8d10c48e0c526069

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
