apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 53c67e32de6184416811cc5869827dc0d81c0d51
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 53c67e32de6184416811cc5869827dc0d81c0d51
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 53c67e32de6184416811cc5869827dc0d81c0d51
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 53c67e32de6184416811cc5869827dc0d81c0d51
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 53c67e32de6184416811cc5869827dc0d81c0d51

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
