apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 2b615a01ff48e858931bf62e81812c7c21fe658a
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 2b615a01ff48e858931bf62e81812c7c21fe658a
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 2b615a01ff48e858931bf62e81812c7c21fe658a
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 2b615a01ff48e858931bf62e81812c7c21fe658a
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 2b615a01ff48e858931bf62e81812c7c21fe658a

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
