apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: CRONJOB-PUBLISH
  newName: njugen/todo-publish
  newTag: 4d2eafa0cdd79ea975727218906880fd5c088354
- name: JOB-BACKUP
  newName: njugen/todo-backup
  newTag: 4d2eafa0cdd79ea975727218906880fd5c088354
- name: TODO-BACKEND
  newName: njugen/todo-backend
  newTag: 4d2eafa0cdd79ea975727218906880fd5c088354
- name: TODO-BROADCASTER
  newName: njugen/todo-broadcaster
  newTag: 4d2eafa0cdd79ea975727218906880fd5c088354
- name: TODO-FRONTEND
  newName: njugen/todo-app
  newTag: 4d2eafa0cdd79ea975727218906880fd5c088354

resources:
- configmap.yaml
- cronjob.yaml
- statefulset.yaml
- ingress.yaml
- service.yaml
- rollout.yaml
