apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-storage-claim
  namespace: project
spec:
  storageClassName: todo-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi