apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    canary:
      steps:
      - setWeight: 25
      - setWeight: 50
      - setWeight: 75
      - setWeight: 100
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: todo-storage-volume
          persistentVolumeClaim:
            claimName: todo-storage-claim
      containers:
        - name: todo-backend
          image: TODO-BACKEND
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: todo-storage-volume
              mountPath: /usr/src/files/images
          envFrom:
            - configMapRef:
                name: project-config
          readinessProbe:
            initialDelaySeconds: 80
            periodSeconds: 5
            httpGet:
               path: /db-diagnosis
               port: 3001
          livenessProbe:
            initialDelaySeconds: 80
            periodSeconds: 5
            httpGet:
               path: /
               port: 3001
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-frontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  strategy:
    canary:
      steps:
      - setWeight: 25
      - setWeight: 50
      - setWeight: 75
      - setWeight: 100
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
        - name: todo-storage-volume
          persistentVolumeClaim:
            claimName: todo-storage-claim
      containers:
        - name: todo-frontend
          image: TODO-FRONTEND
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: todo-storage-volume
              mountPath: /usr/src/files/images
          envFrom:
            - configMapRef:
                name: project-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-broadcaster
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: TODO-BROADCASTER
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: project-config