apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-storage-volume
          configMap:
              name: project-config
      containers:
        - name: todo-app
          image: TODO-FRONTEND
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: todo-storage-volume
              mountPath: /usr/src/files/images
          envFrom:
            - configMapRef:
                name: project-config
          resources:
            limits:
              memory: "120Mi"
              cpu: "100m"
            requests:
              memory: "1Mi"
              cpu: "1m"
        - name: todo-backend
          image: TODO-BACKEND
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: todo-storage-volume
              mountPath: /usr/src/files/images
          envFrom:
            - configMapRef:
                name: project-config
          resources:
            limits:
              memory: "80Mi"
              cpu: "100m"
            requests:
              memory: "1Mi"
              cpu: "1m"