apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cronjobbackup.yaml
  - pv.yaml
  - pvc.yaml
  - ./../../manifests
namespace: the-project-production
patches:
  - path: configmap-patch.yaml
  - path: rollout-patch.yaml