apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: JOB-BACKUP
    newName: njugen/todo-backup
    newTag: e8fce98fe4526af88eafca8d2b7862cd41563151
resources:
  - namespace.yaml
  - cronjobbackup.yaml
  - pv.yaml
  - pvc.yaml
  - ./../../manifests
namespace: the-project-production
patches:
  - path: configmap-patch.yaml
  - path: rollout-patch.yaml